CREATE TABLE IF NOT EXISTS Like (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Type TEXT CHECK( Type IN ('COMMENT','POST') ),
	Liked INTEGER CHECK( Liked IN (0,1) ),
	IdObject INTEGER 
)