CREATE TABLE IF NOT EXISTS Comment (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	ImgUrl TEXT ,
	Content TEXT NOT NULL,
	IdUser INTEGER ,
	IdPost INTEGER ,
	FOREIGN KEY (IdUser) REFERENCES User (Id)
)