CREATE TABLE IF NOT EXISTS Visibilty (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	IdPost INTEGER ,
	Type TEXT CHECK( Type IN ('GROUP','POST') ),
	IdObject INTEGER ,
	FOREIGN KEY (IdPost) REFERENCES Post (Id)
)