CREATE TABLE IF NOT EXISTS Post (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Title TEXT NOT NULL,
	ImgUrl TEXT ,
	Content TEXT NOT NULL,
	IdUser INTEGER ,
	Status TEXT CHECK( Status IN ('PUBLIC','PRIVATE','ALMOST') ),
	IdGroups INTEGER ,
	FOREIGN KEY (IdUser) REFERENCES User (Id),
FOREIGN KEY (IdGroups) REFERENCES Groups (Id)
)