CREATE TABLE IF NOT EXISTS Event (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Title TEXT NOT NULL,
	Description TEXT NOT NULL,
	Option TEXT CHECK( Option IN ('GOING','NOT_GOING') )
)