CREATE TABLE IF NOT EXISTS Followers (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	IdFollower INTEGER ,
	IdFollowee INTEGER ,
		Status TEXT CHECK( Status IN ('PENDING','VALIDATE') ),

	FOREIGN KEY (IdFollower) REFERENCES User (Id),
FOREIGN KEY (IdFollowee) REFERENCES User (Id)
)