CREATE TABLE IF NOT EXISTS Chat (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Type TEXT CHECK( Type IN ('Groups','CHAT') ),
	Sender INTEGER ,
	Receiver INTEGER ,
	Content TEXT NOT NULL,
	FOREIGN KEY (Sender) REFERENCES User (Id)
)