CREATE TABLE IF NOT EXISTS User (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
	Username TEXT ,
	Email TEXT NOT NULL UNIQUE,
	Password TEXT ,
	FirstName TEXT NOT NULL,
	LastName TEXT NOT NULL,
	DateOfBirth TEXT NOT NULL,
	ImageURL TEXT ,
	AboutMe TEXT ,
	Profil TEXT CHECK( Profil IN ('PUBLIC','PRIVATE') ),
	JWT TEXT DEFAULT ''
)